export interface Industry {
  slug: string;
  name: string;
  plural: string;
  headline: string;
  subheadline: string;
  painPoints: string[];
  whatWeBuild: { title: string; desc: string }[];
  demoSlug?: string;
  color: string;
  bg: string;
  resultStat: { value: string; label: string };
}

export const industries: Industry[] = [
  {
    slug: 'barbershops',
    name: 'Barbershop',
    plural: 'Barbershops',
    headline: 'Your Chair Should Always Be Full.',
    subheadline: 'Most barbershops in Detroit are losing walk-ins to shops that show up first on Google. We fix that — and add online booking so your phone stops ringing for appointments.',
    color: '#C9A84C',
    bg: 'rgba(201,168,76,0.1)',
    resultStat: { value: '3×', label: 'More Google calls in 30 days' },
    painPoints: [
      'Invisible on Google Maps when someone searches "barbershop near me"',
      'No online booking — losing customers who don\'t want to call',
      'Reviews are scattered or outdated — harder to trust',
      'No way to show off your cuts before customers walk in',
      'Competing against franchise shops with bigger marketing budgets',
    ],
    whatWeBuild: [
      { title: 'Online Booking System', desc: 'Customers book directly from your website or Google listing — no calls needed. Integrated with your schedule so you\'re never double-booked.' },
      { title: 'Photo Gallery', desc: 'Showcase your best cuts in a high-impact gallery that builds trust before a first visit. Works like an Instagram but lives on your site permanently.' },
      { title: 'Google Business Optimization', desc: 'We claim, verify, and optimize your Google Business Profile so you show up when locals search "barbershop near me" in your neighborhood.' },
      { title: 'AI Chatbot', desc: 'Answers questions about pricing, hours, and booking at midnight — when you\'re closed and a potential client is scrolling.' },
      { title: 'Review Engine', desc: 'Automated follow-up messages after each visit that invite satisfied customers to leave a Google review. More 5-stars, less effort.' },
    ],
    demoSlug: 'detroit-cuts',
  },
  {
    slug: 'restaurants',
    name: 'Restaurant',
    plural: 'Restaurants',
    headline: 'Empty Tables Are a Website Problem.',
    subheadline: 'Diners decide where to eat before they leave the house. If your restaurant isn\'t showing up on Google with a menu, photos, and easy reservation options — they\'re going somewhere else.',
    color: '#E8631A',
    bg: 'rgba(232,99,26,0.1)',
    resultStat: { value: '2×', label: 'Catering inquiries in 60 days' },
    painPoints: [
      'Outdated menu on third-party sites you don\'t control',
      'No direct reservation or catering inquiry system',
      'Zero visibility when tourists or newcomers search nearby',
      'Losing private dining and event revenue to better-known spots',
      'Social media presence that doesn\'t drive real traffic',
    ],
    whatWeBuild: [
      { title: 'Online Menu', desc: 'A fast, mobile-first menu with photos — yours to update instantly without calling a developer. Structured for Google to index every dish.' },
      { title: 'Catering Inquiry Form', desc: 'Structured intake that captures the event type, headcount, date, and budget — so your first conversation is already qualified.' },
      { title: 'Reservation System', desc: 'Direct reservations without third-party fees. Integrate with your host stand or accept requests via email for manual confirmation.' },
      { title: 'Events & Private Dining Page', desc: 'A dedicated page for birthdays, corporate dinners, and buyouts — with its own SEO and inquiry form to capture high-value bookings.' },
      { title: 'AI Chatbot for FAQs', desc: 'Hours, parking, dietary options, corkage fees — the chatbot handles the common questions so your staff handles the guests.' },
    ],
    demoSlug: 'detroits-kitchen',
  },
  {
    slug: 'plumbers',
    name: 'Plumber',
    plural: 'Plumbers & Plumbing Companies',
    headline: 'Emergency Calls Go to Who Shows Up First.',
    subheadline: 'When a pipe bursts at 11 PM, homeowners call the first plumber they find on Google. That could be you — or it\'s your competitor. We build sites that dominate local search for emergency and scheduled plumbing calls.',
    color: '#1E3D8F',
    bg: 'rgba(30,61,143,0.1)',
    resultStat: { value: '+18', label: 'Leads per month on average' },
    painPoints: [
      'Emergency customers calling competitors who rank above you on Google',
      'No lead capture system for non-emergency inquiries',
      'Service area pages that don\'t rank for local searches',
      'Trust gap with new customers who can\'t verify your credentials online',
      'Losing jobs to national franchise services with better web presence',
    ],
    whatWeBuild: [
      { title: 'Emergency Call CTA Above the Fold', desc: 'The single most important element for a plumbing site. Click-to-call on every page, visible before any scrolling — built for panicked homeowners.' },
      { title: 'Service Area Landing Pages', desc: 'Individual pages for every city and neighborhood you serve — Detroit, Dearborn, Southfield, Warren, and beyond. Each one indexed for local searches.' },
      { title: 'Lead Capture Form', desc: 'Structured intake for non-emergency jobs: type of issue, urgency, address, photos. Routes directly to you by email or text.' },
      { title: 'Trust Signals Section', desc: 'License numbers, insurance verification, years in business, and real Google reviews — all in one section that converts skeptics.' },
      { title: 'Google Business Profile', desc: 'Optimized for plumbing-specific searches with service categories, response times, and geo-targeted keywords.' },
    ],
    demoSlug: 'metro-plumbing',
  },
  {
    slug: 'salons',
    name: 'Hair Salon',
    plural: 'Hair Salons & Beauty Studios',
    headline: 'Your Work Should Speak Before You Do.',
    subheadline: 'Clients choose salons based on photos and reviews — long before they call to book. We build gallery-first websites that showcase your artistry and convert visitors into booked appointments.',
    color: '#C9956C',
    bg: 'rgba(201,149,108,0.1)',
    resultStat: { value: '+40%', label: 'New client bookings in month 1' },
    painPoints: [
      'Best work buried on Instagram where it gets lost after 48 hours',
      'No way for new clients to browse stylists before booking',
      'Booking happens over DMs or phone — inefficient and easy to miss',
      'Competition from salons with stronger Google and Yelp presence',
      'No system to ask satisfied clients for Google reviews',
    ],
    whatWeBuild: [
      { title: 'Gallery-First Design', desc: 'High-impact photo layouts that put your best work front and center — styled to match your brand, not a generic template.' },
      { title: 'Stylist Profiles & Specialties', desc: 'Individual pages for each stylist with their portfolio, specialties, availability, and booking link. Helps clients find their perfect match.' },
      { title: 'Online Booking', desc: 'Service selection, stylist selection, date and time — all handled before they walk in. Connected to your schedule system.' },
      { title: 'Natural Hair / Specialty SEO', desc: 'Structured pages targeting your specific services — natural hair, locs, color, braids — so clients searching those terms find you first.' },
      { title: 'Review Engine', desc: 'Post-appointment follow-up that invites happy clients to share their experience on Google. Consistent 5-stars compound over time.' },
    ],
    demoSlug: 'luxe-salon',
  },
  {
    slug: 'contractors',
    name: 'Contractor',
    plural: 'Contractors & Home Services',
    headline: 'Every Job Should Come with Three Referrals.',
    subheadline: 'Homeowners in Detroit hire contractors they trust — and trust is built online before the first call. A professional website with real photos and verifiable reviews turns one job into a steady pipeline.',
    color: '#16a34a',
    bg: 'rgba(22,163,74,0.1)',
    resultStat: { value: '5×', label: 'Quote requests vs. no website' },
    painPoints: [
      'Work speaks for itself but potential clients can\'t see it online',
      'Losing bids to contractors with polished websites and more reviews',
      'No system to follow up with past clients for repeat or referral work',
      'Inconsistent Google Business Profile with missing service info',
      'Phone number hard to find — prospects call a competitor instead',
    ],
    whatWeBuild: [
      { title: 'Project Gallery', desc: 'Before-and-after photos organized by project type. Shows the quality of your work to homeowners before they ever call.' },
      { title: 'Quote Request Form', desc: 'Structured intake: project type, location, timeline, photos. Every submission arrives pre-qualified so you stop wasting time on tire-kickers.' },
      { title: 'Service Pages', desc: 'Dedicated pages for each service you offer — roofing, remodeling, landscaping, HVAC — each optimized for local search terms.' },
      { title: 'License & Insurance Display', desc: 'Your credentials, certifications, and insurance on the homepage. The single biggest converter for homeowners nervous about unlicensed work.' },
      { title: 'Review Automation', desc: 'Post-job follow-up that asks happy clients for reviews while the experience is fresh. Compounds into a dominant local reputation over time.' },
    ],
  },
  {
    slug: 'dentists',
    name: 'Dental Practice',
    plural: 'Dentists & Dental Practices',
    headline: 'Patients Research Before They Book.',
    subheadline: 'Most people choose a dentist based on online reviews and how professional the website looks. If your site feels dated or your Google listing is incomplete, you\'re losing patients to practices that got there first.',
    color: '#0d9488',
    bg: 'rgba(13,148,136,0.1)',
    resultStat: { value: '+25', label: 'New patient inquiries per month' },
    painPoints: [
      'New patient flow dependent on insurance referrals and word of mouth',
      'No online booking — front desk spends hours on scheduling calls',
      'Google reviews sparse compared to competing practices',
      'Insurance and service information buried or hard to find',
      'Website looks like it was built in 2010 — erodes trust instantly',
    ],
    whatWeBuild: [
      { title: 'New Patient Online Booking', desc: 'Appointment requests directly from your site — service type, insurance, preferred date — delivered to your front desk instantly.' },
      { title: 'Services & Insurance Pages', desc: 'Clear, searchable pages for every service you offer and every insurance you accept. Removes the #1 question patients ask before calling.' },
      { title: 'Team & Office Pages', desc: 'Bios for each dentist and hygienist, office photos, and a virtual tour option — all built to reduce new patient anxiety.' },
      { title: 'Local SEO Infrastructure', desc: 'Schema markup, Google Business optimization, and neighborhood-targeted pages that capture "dentist near me" searches in your zip code.' },
      { title: 'Review Engine', desc: 'Post-visit follow-up to satisfied patients — the single most effective way to build Google and Healthgrades reviews consistently.' },
    ],
  },
  {
    slug: 'cleaning-services',
    name: 'Cleaning Service',
    plural: 'Cleaning Services & House Cleaners',
    headline: 'New Clients Are Searching Right Now.',
    subheadline: 'Homeowners and property managers look for cleaning services online before asking a neighbor. If your business isn\'t showing up in those searches, every job you could be booking is going to a competitor.',
    color: '#2563eb',
    bg: 'rgba(37,99,235,0.1)',
    resultStat: { value: '+22', label: 'New client bookings per month' },
    painPoints: [
      'Relying entirely on referrals — no consistent pipeline of new clients',
      'Invisible on Google when someone searches "house cleaning near me"',
      'No online booking — losing clients who want to schedule without calling',
      'Competing against large franchise cleaning companies with bigger marketing budgets',
      'No automated system to collect reviews after each cleaning',
    ],
    whatWeBuild: [
      { title: 'Online Booking & Quote Request', desc: 'Clients select service type, home size, frequency, and preferred date — all captured and routed to you instantly. No phone tag required.' },
      { title: 'Service Area Pages', desc: 'Individual pages for every city and zip code you serve — each optimized for "house cleaning [city]" searches so you capture local demand everywhere you work.' },
      { title: 'Trust-Building Homepage', desc: 'Background check badges, insurance verification, years in business, and real client reviews displayed prominently — converting first-time visitors into booked clients.' },
      { title: 'Before & After Gallery', desc: 'Photo proof of your work builds instant credibility. We structure the gallery so it\'s indexable and shareable, not just a slideshow.' },
      { title: 'Review Automation', desc: 'Post-cleaning follow-up messages that invite satisfied clients to share their experience on Google — the fastest way to build a 5-star reputation.' },
    ],
  },
  {
    slug: 'landscapers',
    name: 'Landscaping Company',
    plural: 'Landscapers & Lawn Care Companies',
    headline: 'Full Schedules Don\'t Happen by Accident.',
    subheadline: 'Homeowners hire landscapers they find online — and they hire the one with the best photos, the most reviews, and the easiest way to get a quote. That could be you, if your website is built for it.',
    color: '#15803d',
    bg: 'rgba(21,128,61,0.1)',
    resultStat: { value: '4×', label: 'Quote requests vs. no website' },
    painPoints: [
      'Seasonal revenue spikes and gaps — no system to book clients in advance',
      'Portfolio of beautiful work that no potential client can see online',
      'Losing bids to landscapers with more Google reviews and a better website',
      'No way to capture leads for recurring maintenance contracts',
      'Phone number hard to find — prospects call someone else instead',
    ],
    whatWeBuild: [
      { title: 'Quote Request System', desc: 'Structured intake that captures service type, property size, location, and urgency — so every lead you receive is pre-qualified before you pick up the phone.' },
      { title: 'Portfolio Gallery', desc: 'Before-and-after project photos organized by service type — lawn care, landscaping, hardscaping, seasonal cleanup. Visual proof sells better than any copy.' },
      { title: 'Service Area Pages', desc: 'Dedicated pages for every community you serve. Each one targets "landscaping [city]" searches so you capture demand across your entire service area.' },
      { title: 'Recurring Service CTA', desc: 'Dedicated landing page and form for seasonal maintenance contracts — the highest-LTV customers in the landscaping business.' },
      { title: 'Google Business Optimization', desc: 'Fully optimized profile with service categories, project photos, and geo-targeted keywords — capturing "landscaper near me" searches before your competitors.' },
    ],
  },
  {
    slug: 'chiropractors',
    name: 'Chiropractic Practice',
    plural: 'Chiropractors & Chiropractic Practices',
    headline: 'New Patients Are One Search Away.',
    subheadline: 'Someone in your zip code searched for a chiropractor in the last hour. Whether they called you or a competitor was decided by whose website ranked higher, looked more trustworthy, and made it easiest to book.',
    color: '#7c3aed',
    bg: 'rgba(124,58,237,0.1)',
    resultStat: { value: '+30', label: 'New patient inquiries per month' },
    painPoints: [
      'New patient acquisition depends too heavily on insurance referrals',
      'Google Business Profile incomplete — losing visibility to nearby practices',
      'No online booking — potential patients call once, don\'t leave a message, move on',
      'Insufficient patient reviews compared to well-established competitors',
      'Services and accepted insurance not clearly listed — patients go elsewhere',
    ],
    whatWeBuild: [
      { title: 'Online Patient Booking', desc: 'New patient appointment requests directly from your site — condition, insurance, preferred time — all routed to your front desk before first contact.' },
      { title: 'Condition & Treatment Pages', desc: 'SEO-structured pages for every condition you treat — back pain, sciatica, sports injuries, headaches. Captures patients searching those exact terms.' },
      { title: 'Insurance & Pricing Clarity', desc: 'A dedicated page listing every insurance you accept and transparent pricing for self-pay patients. Removes the #1 barrier to new patient calls.' },
      { title: 'Doctor & Staff Profiles', desc: 'Professional bios, credentials, and philosophy pages that build patient trust before their first visit — reducing no-shows and cancellations.' },
      { title: 'Review Engine', desc: 'Automated post-visit review requests timed for peak patient satisfaction — consistently building your Google rating above the competition.' },
    ],
  },
  {
    slug: 'insurance-agents',
    name: 'Insurance Agency',
    plural: 'Insurance Agents & Agencies',
    headline: 'Trust Is Built Before the First Call.',
    subheadline: 'Clients shopping for insurance do extensive online research before contacting anyone. Your website is the difference between being on that shortlist and being invisible.',
    color: '#0369a1',
    bg: 'rgba(3,105,161,0.1)',
    resultStat: { value: '3×', label: 'Qualified quote requests per month' },
    painPoints: [
      'Invisible in local searches — "insurance agent near me" leads going to national brands',
      'Website that looks generic — indistinguishable from a thousand other agency sites',
      'No lead capture system — website visitors leave without making contact',
      'Difficulty communicating local expertise vs. 1-800 number competitors',
      'No review strategy — losing trust comparisons to agents with more Google ratings',
    ],
    whatWeBuild: [
      { title: 'Quote Request & Lead Capture', desc: 'Structured intake forms for every insurance product you sell — auto, home, life, commercial. Every submission lands in your inbox pre-qualified.' },
      { title: 'Product & Coverage Pages', desc: 'Clear, educational pages for each insurance product you offer — structured for SEO and designed to answer client questions before they call.' },
      { title: 'Local Trust Signals', desc: 'Years in business, carrier relationships, community involvement, and real client testimonials displayed prominently — differentiating you from national call centers.' },
      { title: 'Google Business Dominance', desc: 'Fully optimized profile targeting "insurance agent [city]" and product-specific searches in your market. Captures high-intent local leads.' },
      { title: 'Review Automation', desc: 'Systematic post-policy follow-up that builds your Google and Facebook review count — the most powerful trust signal in a relationship-driven business.' },
    ],
  },
  {
    slug: 'accounting-firms',
    name: 'Accounting Firm',
    plural: 'Accountants & Accounting Firms',
    headline: 'Clients Choose Expertise. Your Website Proves It.',
    subheadline: 'Small business owners and individuals searching for a CPA or accountant are evaluating your credibility online before they ever call. A weak website costs you clients you never knew you lost.',
    color: '#1d4ed8',
    bg: 'rgba(29,78,216,0.1)',
    resultStat: { value: '+18', label: 'New client inquiries per month' },
    painPoints: [
      'Most new clients come from referrals — no system to attract prospects who don\'t know you',
      'Website looks dated — erodes trust with potential clients evaluating your credibility',
      'Services and specializations not clearly communicated — potential clients choose a competitor',
      'No lead capture — website visitors leave without any way to follow up',
      'Missing from local searches for "CPA near me" or "small business accountant [city]"',
    ],
    whatWeBuild: [
      { title: 'Service & Specialization Pages', desc: 'Dedicated pages for each service area — tax prep, small business accounting, bookkeeping, payroll — structured for SEO and clarity.' },
      { title: 'Client Intake Forms', desc: 'Structured forms for tax, advisory, and bookkeeping inquiries that capture business type, needs, and timeline — so your first call is already qualified.' },
      { title: 'Expertise Positioning', desc: 'Team bios, credentials, industry specializations, and client results displayed in a way that establishes authority before any sales conversation.' },
      { title: 'Local SEO Foundation', desc: 'Schema markup, Google Business optimization, and service-area targeting that captures "accountant near me" searches in your market.' },
      { title: 'Review Strategy', desc: 'Post-engagement follow-up that builds Google reviews from satisfied clients — the social proof that converts researchers into callers.' },
    ],
  },
  {
    slug: 'pet-services',
    name: 'Pet Service Business',
    plural: 'Pet Groomers, Trainers & Boarders',
    headline: 'Pet Owners Are Loyal. But First, They Have to Find You.',
    subheadline: 'Pet owners research grooming, boarding, and training services carefully before trusting anyone with their animals. The businesses that show up first on Google, with the most reviews and the cleanest booking experience, win that loyalty.',
    color: '#d97706',
    bg: 'rgba(217,119,6,0.1)',
    resultStat: { value: '+35%', label: 'New pet owner bookings in 60 days' },
    painPoints: [
      'Fully relying on word-of-mouth — no digital pipeline for new clients',
      'Competitors showing up above you in "dog groomer near me" searches',
      'No online booking — losing time-pressed pet owners who won\'t call during business hours',
      'Reviews are sparse or inconsistent — hard to build trust with first-time visitors',
      'No way to showcase your facility, staff, and happy animal clients online',
    ],
    whatWeBuild: [
      { title: 'Online Booking System', desc: 'Service selection, pet details, date and time — all handled before they arrive. Works for grooming appointments, boarding reservations, and training sessions.' },
      { title: 'Pet Gallery & Staff Profiles', desc: 'Photos of your facility, your team, and happy pets you\'ve served — the visual trust-builders that convert nervous pet owners into booked clients.' },
      { title: 'Service & Pricing Pages', desc: 'Clear pages for every service you offer with transparent pricing — removing the barrier that prevents potential clients from calling.' },
      { title: 'Local SEO Infrastructure', desc: 'Optimized Google Business Profile and neighborhood-targeted pages that put you at the top of "dog groomer near me" and "pet boarding [city]" searches.' },
      { title: 'Review Engine', desc: 'Post-visit follow-up inviting happy pet owners to share their experience on Google — building the trust signals that drive new client bookings consistently.' },
    ],
  },
  {
    slug: 'daycares',
    name: 'Daycare & Childcare Center',
    plural: 'Daycares & Childcare Centers',
    headline: 'Parents Research Every Detail Before Trusting You.',
    subheadline: 'Choosing a daycare is one of the most emotionally charged decisions a parent makes. The centers that make parents feel confident online — with professional sites, real photos, and clear information — fill their enrollment first.',
    color: '#be185d',
    bg: 'rgba(190,24,93,0.1)',
    resultStat: { value: '+20', label: 'Enrollment inquiries per month' },
    painPoints: [
      'Word-of-mouth enrollment is slow — openings sit unfilled for weeks',
      'Parents can\'t find basic information about your program, curriculum, or pricing online',
      'Competing against larger centers with more polished websites and stronger Google presence',
      'No lead capture — interested parents leave the site without ever making contact',
      'Licensing, staff credentials, and safety information not visible — parents choose competitors',
    ],
    whatWeBuild: [
      { title: 'Enrollment Inquiry System', desc: 'Structured intake for prospective parents — child age, start date, schedule needs, program preferences — so every lead is pre-qualified for your follow-up.' },
      { title: 'Program & Curriculum Pages', desc: 'Clear pages describing each age group program, daily schedule, educational philosophy, and activities. Answers the questions parents research before they call.' },
      { title: 'Safety & Credential Showcase', desc: 'Licensing numbers, staff certifications, safety protocols, and inspection results displayed prominently — the trust signals that matter most to cautious parents.' },
      { title: 'Photo Tour & Staff Bios', desc: 'Photos of your facility, outdoor spaces, and classrooms paired with staff profiles that build parent confidence before their first visit.' },
      { title: 'Local SEO', desc: 'Google Business optimization and neighborhood-targeted pages that capture "daycare near me" and "childcare [city]" searches from parents in your area.' },
    ],
  },
  {
    slug: 'retail-stores',
    name: 'Retail Store',
    plural: 'Retail Stores & Boutiques',
    headline: 'Customers Shop Online Before They Walk In.',
    subheadline: 'Most retail purchases start with a Google search — even for local stores. If customers can\'t find you online, can\'t see your inventory, and can\'t confirm your hours, they\'re buying from someone who made it easier.',
    color: '#9333ea',
    bg: 'rgba(147,51,234,0.1)',
    resultStat: { value: '2.5×', label: 'Foot traffic from Google in 90 days' },
    painPoints: [
      'Invisible in "near me" searches — losing local foot traffic to better-ranked competitors',
      'No way to show inventory online — customers don\'t know what you carry',
      'Hours, location, and parking not clearly listed — customers go somewhere more convenient',
      'No loyalty or repeat purchase system — one-time buyers who never return',
      'Losing online customers to Amazon and big-box retailers with better digital presence',
    ],
    whatWeBuild: [
      { title: 'Product Showcase Pages', desc: 'Category and product pages that let customers browse your inventory online — structured for Google Shopping and local product searches.' },
      { title: 'Location & Hours Optimization', desc: 'Your address, hours, parking info, and directions front and center — with Google Maps integration and mobile-first click-to-navigate.' },
      { title: 'Google Business Dominance', desc: 'Fully optimized profile with inventory highlights, regular posts, and geo-targeted keywords that put you at the top of local product searches.' },
      { title: 'Loyalty & Email Capture', desc: 'Email signup, exclusive offer landing pages, and loyalty program information that converts first-time visitors into repeat customers.' },
      { title: 'Local SEO Infrastructure', desc: 'Schema markup for local business and products — helping Google understand exactly what you sell, where you sell it, and why you\'re the best option nearby.' },
    ],
  },
  {
    slug: 'auto-dealerships',
    name: 'Auto Dealership',
    plural: 'Auto Dealerships & Car Lots',
    headline: 'Car Buyers Spend 14 Hours Online Before They Visit.',
    subheadline: 'Auto shoppers research extensively before stepping onto a lot. If your dealership\'s website is slow, hard to navigate, or missing inventory — they\'re visiting a competitor before they ever consider you.',
    color: '#b45309',
    bg: 'rgba(180,83,9,0.1)',
    resultStat: { value: '+45%', label: 'Online lead inquiries in 60 days' },
    painPoints: [
      'Outdated website with slow loading and hard-to-search inventory',
      'Missing from local searches — larger dealerships with better SEO capture your customers',
      'No lead capture for finance inquiries, trade-in valuations, or test drive requests',
      'Negative or sparse Google reviews hurting trust with comparison shoppers',
      'No digital strategy to stand out against franchise brands with national ad budgets',
    ],
    whatWeBuild: [
      { title: 'Inventory Showcase', desc: 'Fast, filterable vehicle listings with photos, specs, pricing, and financing info — built for mobile shoppers who research on their phones.' },
      { title: 'Lead Capture Forms', desc: 'Dedicated forms for test drive requests, trade-in appraisals, financing applications, and general inquiries — capturing every prospect at every stage.' },
      { title: 'Financing & Trade-In Pages', desc: 'Educational pages about financing options and trade-in process — the two biggest questions buyers have before visiting a lot.' },
      { title: 'Local SEO for Auto Searches', desc: '"Used cars [city]", "car dealership near me", "[make] dealer [city]" — we build the page structure and optimization that captures high-intent local buyers.' },
      { title: 'Review Automation', desc: 'Post-purchase review requests that build your Google and DealerRater ratings — the most trusted signals for car buyers in comparison mode.' },
    ],
  },
  {
    slug: 'general-contractors',
    name: 'General Contractor',
    plural: 'General Contractors & Construction Companies',
    headline: 'Every Big Project Starts With a Google Search.',
    subheadline: 'Homeowners and property managers vet contractors online before calling anyone. The GC with the best website, the most reviews, and the clearest proof of quality gets the call — and the contract.',
    color: '#78350f',
    bg: 'rgba(120,53,15,0.1)',
    resultStat: { value: '6×', label: 'Quote requests vs. relying on referrals' },
    painPoints: [
      'All work comes from referrals — no consistent digital lead pipeline',
      'Portfolio of completed projects that no potential client can see online',
      'Losing bids to contractors with polished websites and dozens of 5-star reviews',
      'No lead qualification system — wasting time on tire-kicker inquiries',
      'Licensing and insurance info not visible — losing trust with cautious homeowners',
    ],
    whatWeBuild: [
      { title: 'Project Portfolio', desc: 'High-quality before-and-after photos organized by project type — remodels, additions, commercial builds — with project details that demonstrate scope and quality.' },
      { title: 'Structured Quote Request', desc: 'Intake form that captures project type, location, budget range, timeline, and photos — so every lead you receive is already pre-qualified.' },
      { title: 'Licensing & Insurance Display', desc: 'Your contractor license number, insurance certificates, bonding info, and certifications front and center — the #1 trust signal for homeowners nervous about fly-by-night operators.' },
      { title: 'Service-Specific Pages', desc: 'Dedicated pages for each service you offer — kitchen remodels, additions, commercial construction — each optimized for local search terms.' },
      { title: 'Review Engine', desc: 'Post-project follow-up that systematically builds Google reviews from satisfied clients — compounding into a dominant local reputation over time.' },
    ],
  },
  {
    slug: 'med-spas',
    name: 'Med Spa',
    plural: 'Med Spas & Aesthetic Clinics',
    headline: 'Aesthetics Clients Research Obsessively Before Booking.',
    subheadline: 'Botox, fillers, laser treatments — clients don\'t book these on impulse. They spend hours researching providers, comparing before-and-afters, and reading reviews. The med spa that shows up first with the most compelling presence wins.',
    color: '#be185d',
    bg: 'rgba(190,24,93,0.08)',
    resultStat: { value: '+55%', label: 'New client bookings in first 90 days' },
    painPoints: [
      'Competition from newer med spas with bigger Instagram followings and better-ranked websites',
      'No online booking — losing clients who won\'t call during business hours',
      'Before-and-after photos buried on Instagram instead of driving website conversions',
      'Service menu and pricing not clearly listed — driving potential clients to competitors who are transparent',
      'Google reviews not keeping pace with the quality of your results',
    ],
    whatWeBuild: [
      { title: 'Online Booking & Consultation Requests', desc: 'Service selection, preferred provider, date and time — all handled before a client steps in. Consultation request forms for new clients who want a call first.' },
      { title: 'Treatment & Results Gallery', desc: 'Before-and-after photo galleries organized by treatment — Botox, fillers, laser, body contouring — with results that convert researchers into booked clients.' },
      { title: 'Service & Pricing Pages', desc: 'Clear, detailed pages for every treatment you offer with pricing ranges — the transparency that builds trust and removes the barrier to booking.' },
      { title: 'Provider Profiles', desc: 'Credentials, specializations, and patient outcomes for each provider — differentiating your clinic and helping clients choose the right injector for their goals.' },
      { title: 'Review Automation', desc: 'Post-treatment follow-up that captures Google reviews from satisfied clients while results are fresh — compounding into category dominance on local search.' },
    ],
  },
  {
    slug: 'photography-studios',
    name: 'Photography Studio',
    plural: 'Photographers & Photography Studios',
    headline: 'Your Portfolio Does the Selling. Your Website Gets Them There.',
    subheadline: 'Clients book photographers based on portfolio and personality — but they find photographers on Google. If your website doesn\'t rank, no one ever sees your best work.',
    color: '#1e40af',
    bg: 'rgba(30,64,175,0.1)',
    resultStat: { value: '+40%', label: 'Booking inquiries in 60 days' },
    painPoints: [
      'Best work scattered across Instagram and third-party portfolio sites instead of driving direct bookings',
      'Invisible on Google for "wedding photographer Detroit" and other high-intent searches',
      'No online booking or inquiry system — missing clients who won\'t chase you down',
      'Generic portfolio site that doesn\'t rank, doesn\'t convert, and doesn\'t reflect your brand',
      'Losing bookings to photographers with better websites, not better photography',
    ],
    whatWeBuild: [
      { title: 'Portfolio-First Design', desc: 'A visually striking gallery experience organized by shoot type — weddings, portraits, commercial, events — that showcases your work the way it deserves to be seen.' },
      { title: 'Booking & Inquiry System', desc: 'Date and package inquiry forms that capture event type, date, location, and budget — so every lead you receive is already pre-qualified.' },
      { title: 'Specialty & Package Pages', desc: 'Dedicated pages for each photography service you offer with pricing guidance — structured for SEO and built to convert comparison shoppers.' },
      { title: 'Local SEO for High-Intent Searches', desc: '"Wedding photographer [city]", "portrait photographer near me", "newborn photography [city]" — we build the SEO infrastructure that makes your portfolio findable.' },
      { title: 'Review Engine', desc: 'Post-shoot follow-up that builds Google reviews from happy clients — the most powerful ranking and conversion signal in a referral-heavy business.' },
    ],
  },
];

export function getIndustry(slug: string): Industry | undefined {
  return industries.find(i => i.slug === slug);
}
